### ISSUE TITLE
How to load the data in a right way?

### ISSUE THREAD

**Issue by Wapiti08** [mitre-attack/mitreattack-python#129]
## Expected Behavior
load the downloaded enterprise-attack.json without error

## Actual Behavior
```
 No such file or directory: '/content/xxx
```
## Steps to Reproduce the Problem

from mitreattack.stix20 import MitreAttackData
```
mitre_attack_data = MitreAttackData("https://raw.githubusercontent.com/mitre/cti/master/enterprise-attack/enterprise-attack.json")
technique = mitre_attack_data.get_object_by_attack_id('T1134', 'attack-pattern')
```

**Comment by clemiller** [comment]
Hi @Wapiti08,

`MitreAttackData` doesn't currently support pulling data from a URL; you can download the `enterprise-attack.json` file locally and provide the library with the local file path. Keeping this open in case the team wants to add support for URLs in the future.
