### ISSUE TITLE
[Request] Allow font size in SVG config

### ISSUE THREAD

**Issue by SimonDubex** [mitre-attack/mitreattack-python#160]
### Is your feature request related to a problem?
Currently there is no way to control font sizes when using the “to_svg” function. Similar to the issues mention in the attack navigator forum:
https://github.com/mitre-attack/attack-navigator/issues/484

### Describe the solution you'd like
Add a paramter to the Svg config, which allows you to either use autofill for font size, og manually overwrite it and use a specific font size

### Additional context
This feature is already implemented in attack navigator and should therefore also be implemented in the python module.

**Comment by jondricek** [comment]
Thanks for the suggestion! We'll look at tackling this in the new year sometime.

**Comment by SimonDubex** [comment]
Hi,

Has this been considered yet? we could really use this feature.
