### ISSUE TITLE
Add missing technique fields to attackToExcel

### ISSUE THREAD

**Issue by isaisabel** [mitre-attack/mitreattack-python#17]
As a user, I want to be able to find the full ATT&CK dataset in the excel representation.

Currently multiple domain-specific fields are missing for techniques, including "Impact Type" and "Effective Permissions". The full list can be found in the USAGE document here: https://github.com/mitre/cti/blob/master/USAGE.md#techniques

This was likely caused by the fact that those fields were not listed in the USAGE document until relatively recently.

**Comment by ArtificialErmine** [comment]
Addressed by #18
