### ISSUE TITLE
Group id G0097 and its info is missing

### ISSUE THREAD

**Issue by rishabhsiitk** [mitre-attack/mitreattack-python#20]
This group is available on website `https://attack.mitre.org/groups/`
![image](https://user-images.githubusercontent.com/14132328/125585182-7c3c325c-9065-4348-b516-d23cae5f9535.png)
but when we tried to pull this info via this library(even with latest version `1.2.1`), it's not there. Below is the code snapshot
![image](https://user-images.githubusercontent.com/14132328/125586045-2b4f21ea-3ae5-4505-9c9f-fd5db5ca6293.png)

**Comment by isaisabel** [comment]
Hi @rishabhsiitk,

Bouncing Golf is a mobile group so you wouldn't find it in the Enterprise dataset. Groups and software don't inherently have domains when viewed on the ATT&CK website, so their domain (on the data side of things) is determined by what techniques they map to. Bouncing Golf only maps to mobile techniques and is therefore considered a mobile group and is only included in the mobile data.

If you replace `"enterprise-attack"` with `"mobile-attack"` you will be able to find that group.
