### ISSUE TITLE
Generate usage layers for all groups, software, and mitigations

### ISSUE THREAD

**Issue by isaisabel** [mitre-attack/mitreattack-python#21]
As a user, I want to be able to easily create usage layers (as implemented in #13/#9) for all of the groups, software, or mitigations in the dataset. 

While reasonably easy to run the existing UsageGenerator over a series of object names, building that feature into the library would save effort for users who want to build a full set of layers representing for the ATT&CK knowledge base.

This improvement should include:
- An API that returns a set of Layer objects (either in an array, or in a map of `name/ATT&CK-ID/STIX-ID -> Layer`)
- A CLI which writes the set of layer files into a folder
- Both methods should take the object type (group, software, mitigation) as a parameter.

**Comment by ArtificialErmine** [comment]
Closed by #30
