### ISSUE TITLE
Load custom data over the network

### ISSUE THREAD

**Issue by isaisabel** [mitre-attack/mitreattack-python#22]
As a user of this library, I would like to be able to load custom data over the network as input for the functionalities of this library (e.g attackToExcel, the layer generators in #13). Currently, support for custom data is only allowed via the `local` argument of some of the APIs in this library, so data would need to be fetched separately, saved to a file, and then loaded from that file to be used.

Allowing data to be fetched directly using `requests` would allow me to [integrate `mitreattack-python` with a local ATT&CK Workbench instance](https://github.com/center-for-threat-informed-defense/attack-workbench-frontend/blob/master/docs/integrations.md) since the ATT&CK Workbench exposes a REST API endpoints for fetching the knowledge base in raw STIX.

**Comment by isaisabel** [comment]
Once added, the integration should be documented on the ATT&CK Workbench's [integrations](https://github.com/center-for-threat-informed-defense/attack-workbench-frontend/blob/master/docs/integrations.md) page with some brief examples of use.

**Comment by ArtificialErmine** [comment]
Closed by #41
