### ISSUE TITLE
Field name issue: version should be versions

### ISSUE THREAD

**Issue by isaisabel** [mitre-attack/mitreattack-python#24]
The layerobject's [`_enumerate` function uses the field name `version`](https://github.com/mitre-attack/mitreattack-python/blob/master/mitreattack/navlayers/core/layerobj.py#L335). [Layer format version 4](https://github.com/mitre-attack/attack-navigator/blob/master/layers/LAYERFORMATv4.md) changed this to `versions` (it was correct as `version` prior to layer version 4).

**Comment by ArtificialErmine** [comment]
Patched by #26
