### ISSUE TITLE
Generate a collection index from a set of collections

### ISSUE THREAD

**Issue by isaisabel** [mitre-attack/mitreattack-python#28]
As an individual or organization seeking to share extensions of ATT&CK, I want to be able to generate a [collection index](https://github.com/center-for-threat-informed-defense/attack-workbench-frontend/blob/master/docs/collections.md#collection-indexes) from a set of input collections.

[This script has already been implemented](https://github.com/mitre-attack/attack-stix-data/blob/master/util/generate-collection-index.py), but needs to be ported into this library. Additionally:
- The current implementation only allows a collection index to be created based on collections on the filesystem. The new implementation should also support an array of [STIX 2.1 bundles](https://stix2.readthedocs.io/en/latest/api/stix2.v21.html#stix2.v21.Bundle) as input for the collections. These bundles will need to be validated to contain an x-mitre-collection object so that non-collections are not used as input.
- The CLI of that script should be provided similarly to the CLI of the layer exporters already included in this library.

**Comment by isaisabel** [comment]
#27, #28 and #29 should reside inside of a new module, `collections`, e.g `from mitreattack.collections import bundleToCollection`

**Comment by ArtificialErmine** [comment]
Closed by #32
