### ISSUE TITLE
Add CAPEC IDs to attackToExcel

### ISSUE THREAD

**Issue by isaisabel** [mitre-attack/mitreattack-python#43]
As a user of ATT&CK in Excel, I would like to be able to access the CAPEC ID of a technique (if defined) in the output spreadsheets or DataFrames. [CAPEC IDs](https://github.com/mitre/cti/blob/master/USAGE.md#other-ids) are not currently tracked by attackToExcel, although similar fields such as MTC IDs are.

**Comment by ArtificialErmine** [comment]
Closed by #46
