### ISSUE TITLE
[Bug] Can't use 8 hex digits to specify gradient colors

### ISSUE THREAD

**Issue by Vayper** [mitre-attack/mitreattack-python#57]
ATT&CK Navigator allows the user to specify 8 digits gradient colors (like #ffffff00) with transparency : 
![image](https://user-images.githubusercontent.com/7338706/155580496-6300ee89-cd36-4ff1-b311-d757ef7bfea9.png)

I would like to set programmatically 8 digits colors with mitreattack-python too. 
At the moment, if I specify 8 digits, the last two digits are ignored.

For example:  
```python
input_layer.layer.gradient.colors = ["#ffffff00", "#ff6666ff"]
```
outputs
```json
    "gradient": {
        "colors": [
            "#ffffff",
            "#ff6666"
        ],
```

The last two digits are ignored.

Thanks

**Comment by ArtificialErmine** [comment]
Hey @Vayper - thanks for pointing this out. The libraries currently used for rendering objects in the library don't properly support this transparency at the moment, so fully implementing this may take some time. I will look into building retention for the 8-hex color scheme in the mean time, which should hopefully solve the specific issue you documented here.

Out of curiosity, what is your use case for this functionality? Are you simply trying to generate layers via script, or is there another end goal?

**Comment by Vayper** [comment]
Hey,
Thank you !
I'm simply trying to merge multiple layers together via script. And I like the transparency effect in ATT&CK Navigator :smile:
