### ISSUE TITLE
Document how to create a Layer entirely programatically

### ISSUE THREAD

**Issue by isaisabel** [mitre-attack/mitreattack-python#8]
The Layers module documents how to import and export layers to local JSON. However, it does not document how a user could create a `Layer()`, and then programatically set and modify the properties of the layer. We should add a short tutorial of this to the Layer module documentation. It should include:
- Modifying filter properties
- Setting the gradient colors and upper and lower bounds
- Appending items to the legend
- Adding metadata
- Editing techniques
     - Setting score, comment, color, and metadata on an existing technique
     - Adding a new technique

**Comment by ArtificialErmine** [comment]
Addressed by #11
