### ISSUE TITLE
502 Server Error: Bad Gateway for url: https://cti-taxii.mitre.org/taxii/ [Bug] 

### ISSUE THREAD

**Issue by AlaZegnani** [mitre-attack/mitreattack-python#81]
Hi i'm getting a 502 error trying to access https://cti-taxii.mitre.org/taxii/.

I'm working with navlayers and specifying `source='taxii'` .

**Comment by AlaZegnani** [comment]
it's back up, server issue prob due to outage or something

**Comment by jondricek** [comment]
Yeah, there was an issue last night that we were able to address this morning. Glad it's working now!
