### ISSUE TITLE
[Bug] Filter subtechniques in platforms in attacktoexcel

### ISSUE THREAD

**Issue by seansica** [mitre-attack/mitreattack-python#84]
## Expected Behavior
The AttackToExcel functionality would produce matrices with sub-techniques that are filtered appropriately in the resultant matrices Excel file.

## Actual Behavior
All sub-techniques are displayed regardless of whether they correspond with an existent platform or not.

## Steps to Reproduce the Problem

  1. Follow the instructions listed in the attackToExcel [README](https://github.com/mitre-attack/mitreattack-python#attacktoexcel)

## Possible Solution
Introduce a filter logic mechanism in the `matricesToDf` function that handles filtering sub-techniques from platforms

**Comment by jondricek** [comment]
This was fixed in the 1.5.10 release this morning with this commit: 94b2bc572f8d44bf71598dff9f5210249350a291
