### ISSUE TITLE
[Bug] Excel generation with parameters enterprise-attack / v8.2

### ISSUE THREAD

**Issue by schroray** [mitre-attack/mitreattack-python#88]
## Expected Behavior
Generate all excel files

## Actual Behavior
Generates all excel files but some are empty/non-compliant

## Steps to Reproduce the Problem

  1. python3 attackToExcel.py -domain enterprise-attack -version v8.2 (fails)
  2. python3 attackToExcel.py -domain enterprise-attack -version v11.3 (works fine)
  3. python3 attackToExcel.py (works fine)

## Possible Solution
n/a

**Comment by schroray** [comment]
root@debian11:/media/sf__Shared_RW# python3 attackToExcel.py -domain enterprise-attack -version v8.2
2022-08-30 16:44:32.260 | INFO     | __main__:get_stix_data:69 - Downloading ATT&CK data from github.com/mitre/cti
parsing techniques: 100%|██████████████████████████████████████████████████████████████████████████████| 530/530 [00:00<00:00, 2036.65it/s]
parsing relationships for type=technique: 100%|█████████████████████████████████████████████████████| 9414/9414 [00:00<00:00, 68218.68it/s]
parsing mitigations: 100%|██████████████████████████████████████████████████████████████████████████████| 14/14 [00:00<00:00, 20353.64it/s]
parsing software: 100%|███████████████████████████████████████████████████████████████████████████████| 443/443 [00:00<00:00, 57351.59it/s]
parsing relationships for type=software: 100%|██████████████████████████████████████████████████████| 9414/9414 [00:00<00:00, 86429.20it/s]
parsing groups: 100%|█████████████████████████████████████████████████████████████████████████████████| 109/109 [00:00<00:00, 47533.70it/s]
parsing relationships for type=group: 100%|████████████████████████████████████████████████████████| 9414/9414 [00:00<00:00, 108717.09it/s]
parsing mitigations: 100%|██████████████████████████████████████████████████████████████████████████████| 42/42 [00:00<00:00, 57606.53it/s]
parsing relationships for type=mitigation: 100%|███████████████████████████████████████████████████| 9414/9414 [00:00<00:00, 113323.13it/s]
processing matrix tactics: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.29it/s]
parsing matrices: 100%|██████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:04<00:00,  4.29s/it]
parsing all relationships: 100%|████████████████████████████████████████████████████████████████████| 9414/9414 [00:00<00:00, 76489.64it/s]
[WARNING] (sourceToDf) - No data components or data sources found for domain enterprise-attack. Skipping...
writing formatted files... Traceback (most recent call last):
  File "/media/sf__Shared_RW/attackToExcel.py", line 323, in <module>
    main()
  File "/media/sf__Shared_RW/attackToExcel.py", line 319, in main
    export(args.domain, args.version, args.output, args.remote)
  File "/media/sf__Shared_RW/attackToExcel.py", line 283, in export
    write_excel(dataframes=dataframes, domain=domain, version=version, outputDir=outputDir)
  File "/media/sf__Shared_RW/attackToExcel.py", line 155, in write_excel
    for dfname in dataframes[objType]:
TypeError: 'NoneType' object is not iterable

**Comment by schroray** [comment]
root@debian11:/media/sf__Shared_RW/enterprise-attack-v8.2# ls -la
total 2752
drwxrwx--- 1 root vboxsf    4096 Aug 30 16:29 .
drwxrwx--- 1 root vboxsf    4096 Aug 30 16:30 ..
-rwxrwx--- 1 root vboxsf       0 Aug 30 16:44 enterprise-attack-v8.2-datasources.xlsx
-rwxrwx--- 1 root vboxsf  289315 Aug 30 16:44 enterprise-attack-v8.2-groups.xlsx
-rwxrwx--- 1 root vboxsf   35402 Aug 30 16:44 enterprise-attack-v8.2-matrices.xlsx
-rwxrwx--- 1 root vboxsf  105408 Aug 30 16:44 enterprise-attack-v8.2-mitigations.xlsx
-rwxrwx--- 1 root vboxsf  689393 Aug 30 16:44 enterprise-attack-v8.2-relationships.xlsx
-rwxrwx--- 1 root vboxsf  567459 Aug 30 16:44 enterprise-attack-v8.2-software.xlsx
-rwxrwx--- 1 root vboxsf    9452 Aug 30 16:44 enterprise-attack-v8.2-tactics.xlsx
-rwxrwx--- 1 root vboxsf 1099203 Aug 30 16:44 enterprise-attack-v8.2-techniques.xlsx
-rwxrwx--- 1 root vboxsf       0 Aug 30 16:44 enterprise-attack-v8.2.xlsx
root@debian11:/media/sf__Shared_RW/enterprise-attack-v8.2#

**Comment by jondricek** [comment]
Thanks for the bug report! I _just_ released a new version of `mitreattack-python` to PyPI (v1.6.1) that addresses this issue. You should be able to do a `pip install -U mitreattack-python` and try again and see both a lot more logging in the output but also be able to successfully export Excel files for previous versions of ATT&CK when they don't have the same data types (e.g. Data Sources) as the most current version.

I'm going to close this issue now, but welcome any further discussion or concerns about the topic.
