### ISSUE TITLE
[Bug] Proper Use of Link Dividers

### ISSUE THREAD

**Issue by sko9370** [mitre-attack/mitreattack-python#94]
## Expected Behavior

Add a dictionary to a technique's links as follows: {"divider": true}
The typical technique link dictionary format is: {"label": "blahblah", "url": "blahblah"}

Alternatively, I found LinkDiv(active=True) as the "supported" way to implement dividers, but this adds a dictionary with key value pairs that are not recognized by v4.7.1 Navigator: {"name": "DIVIDER", "value": true}
This method does not cause an error with the Layer function.

## Actual Behavior

When converting a layer dictionary to Layer using "from mitreattack.navlayers.core import Layer", there are errors saying that the divider dictionary does not contain a label (which it's not supposed to because it's a divider). Adding a label key with empty string as value does not solve the problem. Because of the error, the entire technique is not processed and is not included in the output layer.json. Error: "label is not present in link"

## Steps to Reproduce the Problem

1. Manually create a layer dictionary.
2. Add a link to some technique by adding a dictionary with "label" and "url" keys to a technique's links.
3. Add a divider by adding {"divider": true} to the same technique's links.
4. Add another link to the same technique's links.
5. Try to convert the layer dictionary to Layer using "from mitreattack.navlayers.core import Layer"
6. Get error

## Possible Solution

Either prevent the Layer function from erroring for dividers formatted like this: {"divider": true}
or change how LinkDiv(active=True) is reflected, from {"name": "DIVIDER", "value": true} to {"divider": true}

**Comment by clemiller** [comment]
This issue was addressed in PR #95. Let us know if you still run into any problems.
